### ISSUE TITLE
No module named browser error

### ISSUE THREAD

**Issue by jlkreiss** [danielireson/facebook-bulk-group-inviter#1]
Hi, 

I installed the software in a virtualenv with python 2.7.
When a run it, i get a Moduldnotfounderror : No module named browser in  cli/__main__.py line 4, whereas the browser.py file is in the same directory.
See my installation here :+1: 

https://drive.google.com/folderview?id=1jbNc1DDX-N_TB8PwAMnpCGCeFIdA2qbc

Thanks foe your help !

**Comment by danielireson** [comment]
Hi, i'm not too sure what the problem is i'm afraid. Your code looks okay from a brief look at your Google Drive link. I suspect the the problem is related to the python environment and how it's being installed. Unfortunately I don't know what the specific issue is - you should look at posting a question on StackOverflow for help. I hope you can get it sorted. You might also want to disable access to your Google Drive link as it contains the list of email addresses that you're importing.

**Comment by lucy-doan** [comment]
Hi there,

I've just encountered a similar problem. When I tried "from browser import Browser", I got an error message "ModuleNotFoundError: No module named 'browser'".

I'm using Jupyter notebook python 3.7. Is there another module I can use for the similar purpose? Thanks!

For more information, I want to use this module for this purpose of scraping web data: Browser().get_driver().get(URL.format(user_id))

p/s: I'm a beginner here and please help correct me if anything wrong. Thanks!
